### ISSUE TITLE
Video Link

### ISSUE THREAD

**Issue by vanitanaidu** [learn-co-curriculum/oo-ruby-video-object-orientation-overview#2]
The link doesn't work

**Comment by gj** [comment]
Hi @vanitanaidu !

The YouTube link seems to be working now. If you have a minute, would you mind verifying before I close this?

**Comment by curiositypaths** [comment]
Hi there,

The YouTube link seems to be working now. If you are still not able to view the video please reopen the issue and provide the steps required to reproduce the issue

As always, thanks for contributing! 💙
